# Generated by Django 6.0.4 on 2026-04-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaintColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color_name', models.TextField()),
                ('color_codes', models.TextField()),
                ('color_hex', models.CharField(blank=True, default='', max_length=10)),
                ('normalized_manufacturer', models.CharField(db_index=True, max_length=100)),
                ('normalized_model', models.CharField(db_index=True, max_length=100)),
                ('color_group', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['normalized_manufacturer', 'normalized_model', 'year', 'color_group'], name='lookup_pain_normali_53ee3e_idx')],
            },
        ),
    ]
