# Generated by Django 6.0.4 on 2026-04-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('registration', models.CharField(db_index=True, max_length=10)),
                ('make', models.CharField(blank=True, default='', max_length=50)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, default='', max_length=50)),
                ('vin', models.CharField(blank=True, default='', max_length=17)),
                ('paint_code', models.CharField(blank=True, default='', max_length=50)),
                ('paint_description', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.CharField(choices=[('vdg', 'VDG'), ('partslink24', 'Partslink24'), ('manual', 'Manual'), ('none', 'None')], default='none', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('lookup_duration_ms', models.IntegerField(blank=True, null=True)),
                ('vdg_paint_called', models.BooleanField(default=False)),
                ('vdg_vehicle_called', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('email_sent', models.BooleanField(default=False)),
                ('manual_lookup_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'registration'], name='lookup_sear_timesta_0b445b_idx'), models.Index(fields=['provider', 'success'], name='lookup_sear_provide_9dd787_idx'), models.Index(fields=['success', '-timestamp'], name='lookup_sear_success_15a914_idx')],
            },
        ),
    ]
