# Generated by Django 6.0.4 on 2026-04-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Search', 'verbose_name_plural': 'Searches'},
        ),
        migrations.AddField(
            model_name='search',
            name='vehicle_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
