# Generated by Django 6.0.4 on 2026-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_alter_search_options_search_vehicle_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='vdg_balance_after_call',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
