# Generated by Django 6.0.4 on 2026-05-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_search_vdg_balance_after_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintSwatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('hex', models.CharField(max_length=7)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('applicable_models', models.JSONField(default=list)),
                ('model_families', models.JSONField(default=list)),
                ('color_group', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('year_min', models.IntegerField(blank=True, null=True)),
                ('year_max', models.IntegerField(blank=True, null=True)),
                ('sources_count', models.IntegerField(default=1)),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paint swatch',
                'verbose_name_plural': 'Paint swatches',
                'indexes': [models.Index(fields=['manufacturer', 'code'], name='lookup_pain_manufac_f04dd2_idx'), models.Index(fields=['manufacturer', 'code', 'color_group'], name='lookup_pain_manufac_743141_idx')],
                'constraints': [models.UniqueConstraint(fields=('manufacturer', 'code', 'hex'), name='lookup_paintswatch_uniq')],
            },
        ),
    ]
