# Generated by Django 5.2.14 on 2026-05-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_paintswatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='vdg_combined_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search',
            name='vdg_paint_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search',
            name='vdg_vehicle_returned',
            field=models.BooleanField(default=False),
        ),
    ]
