# Generated by Django 5.2.14 on 2026-05-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0006_backfill_combined_call_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='vdg_paint_called',
        ),
        migrations.RemoveField(
            model_name='search',
            name='vdg_vehicle_called',
        ),
    ]
