# Generated by Django 5.2.14 on 2026-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0007_drop_old_call_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='device',
            field=models.CharField(blank=True, db_index=True, default='', max_length=8),
        ),
    ]
