# Generated by Django 6.0.4 on 2026-06-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0009_backfill_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='search',
            name='pl24_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search',
            name='pl24_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search',
            name='recovery_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search',
            name='recovery_duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='vdg_retry_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='search',
            name='provider',
            field=models.CharField(choices=[('vdg', 'VDG'), ('vdg_retry', 'VDG (retry)'), ('partslink24', 'Partslink24'), ('manual', 'Manual'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
