# Generated by Django 6.0.4 on 2026-06-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0010_search_recovery_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='vdg_combined_called',
        ),
    ]
