# Generated by Django 6.0.4 on 2026-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0011_remove_vdg_combined_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='recovery_name_only',
            field=models.BooleanField(default=False),
        ),
    ]
