# Generated by Django 6.0.4 on 2026-06-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0012_search_recovery_name_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('all_names', models.JSONField(default=list)),
                ('normalized_names', models.JSONField(default=list)),
                ('hex', models.CharField(blank=True, default='', max_length=7)),
                ('color_group', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('models_list', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paint lookup',
                'verbose_name_plural': 'Paint lookups',
            },
        ),
        migrations.RemoveIndex(
            model_name='paintswatch',
            name='lookup_pain_manufac_f04dd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='paintswatch',
            name='lookup_pain_manufac_743141_idx',
        ),
        migrations.RemoveConstraint(
            model_name='paintswatch',
            name='lookup_paintswatch_uniq',
        ),
        migrations.DeleteModel(
            name='PaintSwatch',
        ),
        migrations.AddIndex(
            model_name='paintlookup',
            index=models.Index(fields=['manufacturer', 'code'], name='lookup_pain_manufac_4c7e23_idx'),
        ),
        migrations.AddIndex(
            model_name='paintlookup',
            index=models.Index(fields=['manufacturer', 'color_group'], name='lookup_pain_manufac_74e323_idx'),
        ),
        migrations.AddConstraint(
            model_name='paintlookup',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'code'), name='lookup_paintlookup_uniq'),
        ),
    ]
