# Generated by Django 6.0.4 on 2026-06-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0014_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='enriched_from',
            field=models.CharField(blank=True, choices=[('', 'Not enriched'), ('code', 'Code from database'), ('name', 'Name from database')], default='', max_length=8),
        ),
    ]
