# Generated by Django 6.0.4 on 2026-06-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0015_search_enriched_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='vdg_transaction_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]