# Generated by Django 6.0.6 on 2026-07-16 15:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0016_search_vdg_transaction_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='blocked_ips',
            field=models.TextField(blank=True, default='', help_text='IP addresses to refuse (one per line or comma-separated).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='blocked_regs',
            field=models.TextField(blank=True, default='', help_text='Registrations to refuse (one per line or comma-separated).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='blocked_user_agents',
            field=models.TextField(blank=True, default='', help_text='User-agent substrings to refuse (one per line). Case-insensitive match.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='budget_tripped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='budget_tripped_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='daily_budget_gbp',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Max VDG spend per day (London time). 0 = no limit.', max_digits=8),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='payments_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
