# Generated by Django 6.0.6 on 2026-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0017_siteconfig_budget_blocklists_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='VrmCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(db_index=True, max_length=10, unique=True)),
                ('payload', models.JSONField()),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'VRM cache entry',
                'verbose_name_plural': 'VRM cache entries',
            },
        ),
        migrations.AlterField(
            model_name='search',
            name='provider',
            field=models.CharField(choices=[('vdg', 'VDG'), ('vdg_retry', 'VDG (retry)'), ('partslink24', 'Partslink24'), ('manual', 'Manual'), ('cache', 'Cache'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
