# Generated by Django 6.0.6 on 2026-08-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0018_vrmcache_alter_search_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='customer_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='search',
            name='manual_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='search',
            name='no_code_available',
            field=models.BooleanField(default=False),
        ),
    ]
