# Generated by Django 6.0.6 on 2026-08-01 17:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0019_search_manual_context_and_no_code_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='daily_budget_gbp',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Max VDG spend per day (London time). 0 = no limit.', max_digits=8),
        ),
    ]
