# Generated by Django 6.0.7 on 2026-08-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0020_alter_siteconfig_daily_budget_gbp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='blocked_user_agents',
        ),
    ]
