# Generated by Django 6.0.7 on 2026-08-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0022_set_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='vdg_retry_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
