# Generated by Django 6.0.7 on 2026-08-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0023_add_vdg_retry_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='paid_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search',
            name='paywalled',
            field=models.BooleanField(default=False),
        ),
    ]
