# Generated by Django 6.0.7 on 2026-08-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0024_add_paywall_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='unsupported_makes',
            field=models.TextField(blank=True, default='', help_text='Makes we cannot resolve a paint code for — one per line or comma-separated. A lookup for these is refused BEFORE any paid VDG call, and the visitor is told immediately instead of waiting for a lookup that cannot succeed. Matching ignores case, spaces and hyphens, so "MERCEDES-BENZ", "Mercedes Benz" and "mercedesbenz" are the same entry. Leave empty to disable.'),
        ),
    ]
