# Generated by Django 6.0.7 on 2026-08-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0025_add_unsupported_makes'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='pl24_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
