# Generated by Django 6.0.7 on 2026-08-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0026_add_pl24_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='access_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='access_keys',
            field=models.TextField(blank=True, default='', help_text='Trade / unlimited access. One per line as key:label, e.g. "a7f3k9:Daves Bodyshop". Share coloureg.com/?key=a7f3k9 — clicking it once exempts that browser from the hourly search limit. Delete a line to revoke just that person. The label is recorded on each lookup so you can see who used it.'),
        ),
    ]
