# Generated by Django 6.0.7 on 2026-08-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0027_add_access_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='pl24_outcome',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
