# Generated by Django 6.0.7 on 2026-08-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0028_search_pl24_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='oneauto_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='oneauto_outcome',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
