# Generated by Django 6.0.7 on 2026-08-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0029_search_oneauto_cost_search_oneauto_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='pl24_started_because',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
