# Generated by Django 6.0.7 on 2026-08-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0030_search_pl24_started_because'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='oneauto_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='search',
            name='oneauto_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='search',
            name='pl24_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='search',
            name='vdg_paint_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
