# Generated by Django 6.0.7 on 2026-08-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0031_search_oneauto_code_search_oneauto_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='provider',
            field=models.CharField(choices=[('vdg', 'VDG'), ('vdg_retry', 'VDG (retry)'), ('partslink24', 'Partslink24'), ('oneauto', 'One Auto'), ('manual', 'Manual'), ('cache', 'Cache'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
