# Generated by Django 6.0.7 on 2026-08-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0033_alter_search_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='provider',
            field=models.CharField(choices=[('vdg', 'VDG (bundle)'), ('vdg_retry', 'VDG'), ('partslink24', 'Partslink24'), ('oneauto', 'OneAuto'), ('manual', 'Manual'), ('cache', 'Cache'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
