# Generated by Django 6.0.7 on 2026-08-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0035_create_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='origin_gate_mode',
            field=models.CharField(choices=[('observe', 'Observe — log only, trust headers as before'), ('enforce', 'Enforce — only trust headers from Cloudflare')], default='observe', max_length=10),
        ),
    ]
