# Generated by Django 6.0.7 on 2026-08-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0036_siteconfig_origin_gate_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='origin_gate_auto_reverted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
