# Generated by Django 6.0.7 on 2026-08-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0037_siteconfig_origin_gate_auto_reverted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='origin_gate_mode',
            field=models.CharField(choices=[('observe', 'Observe — log only, trust headers as before'), ('enforce', 'Enforce — only trust headers from Cloudflare'), ('block', 'Block — refuse anything not from Cloudflare')], default='observe', max_length=10),
        ),
    ]
