# Generated by Django 6.0.7 on 2026-08-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0038_alter_siteconfig_origin_gate_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='oneauto_second_chance',
            field=models.CharField(blank=True, choices=[('empty', 'Fired, returned nothing'), ('won', 'Fired, produced the code')], default='', help_text='Blank = no second One Auto call was made.', max_length=8),
        ),
        migrations.AddField(
            model_name='search',
            name='second_chance_after_race',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search',
            name='vdg_second_chance',
            field=models.CharField(blank=True, choices=[('empty', 'Fired, returned nothing'), ('won', 'Fired, produced the code')], default='', help_text='Blank = no second VDG paint call was made.', max_length=8),
        ),
    ]
