# Generated by Django 6.0.7 on 2026-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0040_alter_search_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorPaintCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(db_index=True, max_length=60)),
                ('colour_name', models.CharField(blank=True, max_length=200)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('model_text', models.CharField(blank=True, max_length=200)),
                ('source_registration', models.CharField(blank=True, max_length=20)),
                ('source_search_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['manufacturer', 'code'], name='lookup_oper_manufac_85417e_idx'), models.Index(fields=['manufacturer', 'normalized_name'], name='lookup_oper_manufac_955b56_idx')],
            },
        ),
    ]
