# Generated by Django 6.0.7 on 2026-09-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0041_operatorpaintcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='provider',
            field=models.CharField(choices=[('vdg', 'VDG (pre-15 Aug)'), ('vdg_retry', 'VDG'), ('partslink24', 'Partslink24'), ('oneauto', 'OneAuto'), ('ezyvin', 'Ezyvin'), ('manual', 'Manual'), ('cache', 'Cache'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
