# Generated by Django 6.0.7 on 2026-09-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0042_alter_search_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='ezyvin_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='ezyvin_outcome',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='search',
            name='ezyvin_started_because',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
