# Generated by Django 6.0.7 on 2026-09-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0043_search_ezyvin_credits_search_ezyvin_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorpaintcode',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='operatorpaintcode',
            name='previous_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
