# Generated by Django 6.0.7 on 2026-09-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0044_operatorpaintcode_needs_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ezyvin_balance_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ezyvin_credit_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
