# Generated by Django 6.0.7 on 2026-09-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0045_siteconfig_ezyvin_balance_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ezyvin_usage_at_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
