# Generated by Django 6.0.7 on 2026-09-11 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0046_siteconfig_ezyvin_usage_at_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintCodeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(blank=True, default='', max_length=20)),
                ('manufacturer', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('colour_name', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.CharField(choices=[('wrong_colour', 'The colour name looks wrong'), ('wrong_code', 'The paint code looks wrong'), ('other', 'Something else')], default='other', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('new', 'New'), ('actioned', 'Actioned'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=12)),
                ('operator_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_reports', to='lookup.search')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['manufacturer', 'code'], name='lookup_pain_manufac_3932ae_idx')],
            },
        ),
    ]
