# Generated by Django 6.0.7 on 2026-09-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0047_paintcodereport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paintcodereport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reported paint code', 'verbose_name_plural': 'Reported paint codes'},
        ),
    ]
