# Generated by Django 6.0.7 on 2026-09-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0048_alter_paintcodereport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='vdg_balance_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vdg_balance_manual_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
