# Generated by Django 6.0.7 on 2026-09-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0049_siteconfig_vdg_balance_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='gate_reason',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12),
        ),
    ]
