# Generated by Django 6.0.7 on 2026-09-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0050_search_gate_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='name_match_codes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='search',
            name='name_match_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
