# Generated by Django 6.0.7 on 2026-09-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0051_search_name_match_codes_search_name_match_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ip_alert_threshold',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
