# Generated by Django 6.0.8 on 2026-09-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0052_siteconfig_ip_alert_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='mmw_agreed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='mmw_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search',
            name='mmw_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='search',
            name='mmw_colour',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='search',
            name='mmw_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='mmw_outcome',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='search',
            name='mmw_used',
            field=models.BooleanField(default=False),
        ),
    ]
