# Generated by Django 6.0.8 on 2026-09-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0053_search_mmw_agreed_search_mmw_attempted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='provider',
            field=models.CharField(choices=[('vdg', 'VDG (pre-15 Aug)'), ('vdg_retry', 'VDG'), ('partslink24', 'Partslink24'), ('oneauto', 'OneAuto'), ('ezyvin', 'Ezyvin'), ('mmw', 'mmw'), ('manual', 'Manual'), ('cache', 'Cache'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
