# Generated by Django 6.0.8 on 2026-09-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0054_alter_search_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='pl24_slot',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='pl24_via',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
