# Generated by Django 6.0.8 on 2026-09-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0055_search_pl24_slot_search_pl24_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='client_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
