# Generated by Django 6.0.8 on 2026-09-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0056_search_client_duration_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintlookup',
            name='locked_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
