# Generated by Django 6.0.8 on 2026-09-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0057_paintlookup_locked_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintlookup',
            name='operator_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paintlookup',
            name='suppressed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
