# Generated by Django 6.0.8 on 2026-09-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0058_paintlookup_operator_names_paintlookup_suppressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='ezyvin_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='search',
            name='ezyvin_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
