# Generated by Django 6.0.8 on 2026-09-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0059_search_ezyvin_code_search_ezyvin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='pl24_error',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='search',
            name='pl24_http_status',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
