# Generated by Django 6.0.8 on 2026-09-27 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0060_search_pl24_http_status_pl24_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(db_index=True, max_length=10)),
                ('paint_code', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(db_index=True, default='pending', max_length=10)),
                ('painted', models.CharField(blank=True, default='', max_length=200)),
                ('file_key', models.CharField(blank=True, default='', max_length=100)),
                ('verdict', models.CharField(blank=True, default='', max_length=10)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('seconds', models.FloatField(blank=True, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('shown_at', models.DateTimeField(blank=True, null=True)),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_pictures', to='lookup.search')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('registration', 'paint_code'), name='one_car_picture_per_paint')],
            },
        ),
    ]
