# Generated by Django 6.0.8 on 2026-09-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0061_car_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='email_picture',
            field=models.BooleanField(default=False),
        ),
    ]
