# Generated by Django 6.0.8 on 2026-09-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0062_search_email_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpicture',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
