# Generated by Django 6.0.8 on 2026-10-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0063_car_picture_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='provider',
            field=models.CharField(choices=[('vdg', 'VDG (pre-15 Aug)'), ('vdg_retry', 'VDG'), ('partslink24', 'Partslink24'), ('oneauto', 'OneAuto'), ('ezyvin', 'Ezyvin'), ('mmw', 'MMW'), ('manual', 'Manual'), ('cache', 'Cache'), ('remembered', 'Remembered (3 months)'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
